var armor_coverage = {"Body":{"zone":"body","coverage":["Sk","Nk","Fa","Ft","Ha","Ua","Sh","Tx","Ab","Hp","Gr","Fo","El","Th","Kn","Ca"]},
"Skull":{"zone":"head","coverage":["Sk","Fa"]},
"Cap":{"zone":"head","coverage":["Sk"]},
"Hat":{"zone":"head","coverage":["Sk"]},
"Cowl":{"zone":"head","coverage":["Sk","Nk"]},
"Cowl(long)":{"zone":"head","coverage":["Sk","Nk","Sh"]},
"Hood":{"zone":"head","coverage":["Sk","Nk"]},
"Halfhelm":{"zone":"head","coverage":["Sk"]},
"Three-quarter helm":{"zone":"head","coverage":["Sk","Fa"]},
"Greathelm":{"zone":"head","coverage":["Sk","Fa","Nk"]},
"Cloak":{"zone":"clok","coverage":["Sh","Tx","Hp","Ua","Gr"]},
"Cloak, hood":{"zone":"clok","coverage":["SK","Nk","Sh","Tx","Hp","Ua","Gr"]},
"Cloak(long), hood":{"zone":"body","coverage":["Sk","Nk","Sh","Tx","Ab","Hp","Gr","Th","Kn","Ua"]},
"Robe":{"zone":"robe","coverage":["Ua","Sh","Tx","Ab","Hp","Gr","Fo","El","Th","Kn","Ca"]},
"Robe, hood":{"zone":"robe","coverage":["Sk","Nk","Ua","Sh","Tx","Ab","Hp","Gr","Fo","El","Th","Kn","Ca"]},
"Dress(shortsleeve)":{"zone":"robe","coverage":["Ua","Sh","Tx","Ab","Hp","Gr","Th","Kn","Ca"]},
"Dress(longsleeve)":{"zone":"robe","coverage":["Fo","El","Ua","Sh","Tx","Ab","Hp","Gr","Th","Kn","Ca"]},
"Surcoat":{"zone":"robe","coverage":["Sh","Tx","Ab","Hp","Gr","Th"]},
"Tunic":{"zone":"body","coverage":["Ua","Sh","Tx","Ab","Hp","Gr"]},
"Tunic(long)":{"zone":"body","coverage":["Ua","Sh","Tx","Ab","Hp","Gr","Th"]},
"Shirt":{"zone":"body","coverage":["Fo","El","Ua","Sh","Tx","Ab","Hp","Gr"]},
"Shirt(long)":{"zone":"body","coverage":["Fo","El","Ua","Sh","Tx","Ab","Hp","Gr","Th"]},
"Vest":{"zone":"body","coverage":["Sh","Tx","Ab"]},
"Breastplate":{"zone":"thor","coverage":["Tx","Ab"]},
"Backplate":{"zone":"thor","coverage":["Tx","Ab"]},
"Cuirass":{"zone":"thor","coverage":["Tx","Ab"]},
"Gambeson":{"zone":"body","coverage":["Fo","El","Ua","Sh","Tx","Ab","Hp","Gr","Th"]},
"Byrnie":{"zone":"body","coverage":["Ua","Sh","Tx","Ab","Hp","Gr"]},
"Byrnie(long)":{"zone":"body","coverage":["Ua","Sh","Tx","Ab","Hp","Gr","Th"]},
"Hauberk":{"zone":"body","coverage":["Fo","El","Ua","Sh","Tx","Ab","Hp","Gr","Th"]},
"Hauberk(shortsleeve)":{"zone":"body","coverage":["Ua","Sh","Tx","Ab","Hp","Gr","Th"]},
"Gloves":{"zone":"hand","coverage":["Ha"]},
"Gauntlets":{"zone":"hand","coverage":["Ha"]},
"Mittens":{"zone":"hand","coverage":["Ha"]},
"Shorts":{"zone":"thor","coverage":["Hp", "Gr","Th"]},
"Loincloth":{"zone":"thor","coverage":["Hp","Gr"]},
"Skirt(mini)":{"zone":"thor","coverage":["Hp","Gr"]},
"Skirt(short)":{"zone":"thor","coverage":["Hp","Gr","Th"]},
"Skirt(mid)":{"zone":"thor","coverage":["Hp","Gr","Th","Kn"]},
"Skirt(long)":{"zone":"thor","coverage":["Hp","Gr","Th","Kn","Ca"]},
"Pants":{"zone":"legs","coverage":["Hp","Gr","Th","Kn","Ca"]},
"Leggings":{"zone":"legs","coverage":["Hp","Gr","Th","Kn","Ca","Ft"]},
"Boots, calf":{"zone":"feet","coverage":["Ca","Ft"]},
"Boots, knee":{"zone":"feet","coverage":["Kn","Ca","Ft"]},
"Shoes":{"zone":"feet","coverage":["Ft"]},
"Sandals":{"zone":"feet","coverage":["Ft"]},
"Gorget":{"zone":"head","coverage":["Nk"]},
"Ailettes":{"zone":"aile","coverage":["Sh"]},
"Rerebraces":{"zone":"rere","coverage":["Ua"]},
"Coudes":{"zone":"coud","coverage":["El"]},
"Vambraces":{"zone":"vamb","coverage":["Fo"]},
"Kneecops":{"zone":"knee","coverage":["Kn"]},
"Greaves":{"zone":"grev","coverage":["Ca"]}}
