var prices = {"Skull, bone":{"price":0,"weight":0},
"Halfhelm, kurbul":{"price":20,"weight":1.0},
"Halfhelm, ring":{"price":28,"weight":1.0},
"Halfhelm, plate":{"price":100,"weight":3.2},
"Three-quarter helm, plate":{"price":175,"weight":5.6},
"Greathelm, plate":{"price":275,"weight":8.8},
"Boots, knee, cloth":{"price":44,"weight":2.8},
"Boots, knee, leather":{"price":76,"weight":3.8},
"Boots, calf, cloth":{"price":38,"weight":2.2},
"Boots, calf, leather":{"price":64,"weight":3.2},              
"Breastplate, kurbul":{"price":60,"weight":3.0},
"Backplate, kurbul":{"price":60,"weight":3.0},
"Cuirass, kurbul":{"price":120,"weight":6.0},           
"Breastplate, plate":{"price":300,"weight":9.6},
"Backplate, plate":{"price":300,"weight":9.6},
"Cuirass, plate":{"price":600,"weight":19.2},            
"Byrnie, ring":{"price":308,"weight":17.6},
"Byrnie, mail":{"price":660,"weight":22.0},
"Byrnie, scale":{"price":440,"weight":30.8},
"Byrnie(long), ring":{"price":365,"weight":19.6},
"Byrnie(long), mail":{"price":760,"weight":26.0},
"Byrnie(long), scale":{"price":500,"weight":34.8},
"Cap, cloth":{"price":8,"weight":0.4},
"Cap, leather":{"price":16,"weight":0.8},
"Cap, quilt":{"price":16,"weight":1.2},
"Cloak, cloth":{"price":100,"weight":6.6},
"Cloak, leather":{"price":134,"weight":9},
"Cloak, hood, cloth":{"price":115,"weight":8.6},
"Cloak, hood, leather":{"price":140,"weight":11},
"Cloak(long), cloth":{"price":120,"weight":8.8},
"Cloak(long), leather":{"price":150,"weight":12.0},
"Cloak(long), hood, cloth":{"price":140,"weight":10.8},
"Cloak(long), hood, leather":{"price":170,"weight":14.0},
"Cowl, cloth":{"price":10,"weight":0.8},
"Cowl, leather":{"price":12,"weight":1.6},
"Cowl, quilt":{"price":32,"weight":2.4},
"Cowl, mail":{"price":120,"weight":4.0},
"Cowl(long), cloth":{"price":15,"weight":1.2},
"Cowl(long), leather":{"price":18,"weight":2.4},
"Cowl(long), quilt":{"price":42,"weight":3.6},
"Cowl(long), mail":{"price":180,"weight":6.0},              
"Dress(shortsleeve), cloth":{"price":150,"weight":7.8},
"Dress(longsleeve), cloth":{"price":160,"weight":8.2},
"Gambeson, quilt":{"price":200,"weight":19.5},
"Gloves, cloth":{"price":15,"weight":0.4},
"Gauntlets, leather":{"price":16,"weight":0.8},
"Gauntlets, ring":{"price":28,"weight":1.6},
"Mittens, mail":{"price":60,"weight":2.0},              
"Hat, cloth":{"price":16,"weight":0.5},
"Hat, leather":{"price":28,"weight":1.2},
"Hauberk, ring":{"price":420,"weight":26},
"Hauberk, mail":{"price":900,"weight":27.0},
"Hauberk, scale":{"price":600,"weight":50},
"Hauberk(shortsleeve), ring":{"price":399,"weight":24},
"Hauberk(shortsleeve), mail":{"price":855,"weight":26.0},
"Hauberk(shortsleeve), scale":{"price":570,"weight":45.5},              
"Hood, cloth":{"price":16,"weight":0.8},
"Hood, leather":{"price":12,"weight":1.6},
"Hood, quilt":{"price":32,"weight":2.4},
"Leggings, cloth":{"price":88,"weight":4.4},
"Leggings, leather":{"price":176,"weight":8.8},
"Leggings, quilt":{"price":184,"weight":9.2},
"Leggings, ring":{"price":308,"weight":17.6},
"Leggings, mail":{"price":615,"weight":22.0},              
"Loincloth, cloth":{"price":20,"weight":1.0},
"Loincloth, leather":{"price":40,"weight":2.0},
"Loincloth, fur":{"price":40,"weight":2.4},
"Pants, cloth":{"price":100,"weight":4.0},
"Pants, leather":{"price":165,"weight":7.0},
"Pants, quilt":{"price":174,"weight":8.2},
"Pants, ring":{"price":280,"weight":16.4},
"Pants, mail":{"price":184,"weight":20.5},              
"Robe, cloth":{"price":156,"weight":7.8},
"Robe, hood, cloth":{"price":156,"weight":7.8},
"Sandals, leather":{"price":8,"weight":1},              
"Shirt, cloth":{"price":100,"weight":5.2},
"Shirt, leather":{"price":120,"weight":9.8},
"Shirt, quilt":{"price":200,"weight":15.0},
"Shirt(long), cloth":{"price":100,"weight":6.8},
"Shirt(long), leather":{"price":120,"weight":11.8},
"Shirt(long), quilt":{"price":200,"weight":17.5},
"Shoes, cloth ":{"price":12,"weight":1},
"Shoes, leather":{"price":24,"weight":1.2},              
"Shorts, cloth":{"price":40,"weight":2.0},
"Shorts, leather":{"price":60,"weight":4.0},
"Shorts, fur":{"price":60,"weight":4.8}, 
"Skirt(mini), cloth":{"price":20,"weight":1.0},
"Skirt(mini), leather":{"price":30,"weight":1.4},
"Skirt(short), cloth":{"price":20,"weight":2.0},
"Skirt(short), leather":{"price":30,"weight":2.8},
"Skirt(mid), cloth":{"price":20,"weight":3.0},
"Skirt(mid), leather":{"price":30,"weight":4.2},
"Skirt(long), cloth":{"price":20,"weight":4.0},
"Skirt(long), leather":{"price":30,"weight":5.6},              
"Surcoat, cloth":{"price":104,"weight":5.2},
"Surcoat, leather":{"price":208,"weight":10.4},
"Tunic, cloth":{"price":88,"weight":4.4},
"Tunic, leather":{"price":114,"weight":8.8},
"Tunic, quilt":{"price":176,"weight":13.2},
"Tunic(long), cloth":{"price":100,"weight":4.8},
"Tunic(long), leather":{"price":125,"weight":9.2},
"Tunic(long), quilt":{"price":200,"weight":15.6},
"Vest, cloth":{"price":56,"weight":2.8},
"Vest, leather":{"price":112,"weight":5.6},
"Vest, fur":{"price":112,"weight":7.0},
"Vest, quilt":{"price":112,"weight":7.0},
"Vest, scale":{"price":280,"weight":19.6},
"Ailettes, kurbul":{"price":20,"weight":1.0},
"Ailettes, plate":{"price":100,"weight":3.2},
"Coudes, kurbul":{"price":10,"weight":0.5},
"Coudes, plate":{"price":50,"weight":1.6},               
"Gorget, kurbul":{"price":5,"weight":0.5},
"Gorget, plate":{"price":50,"weight":2.0},
"Greaves, kurbul":{"price":50,"weight":2.5},
"Greaves, plate":{"price":250,"weight":8.8},
"Kneecops, kurbul":{"price":15,"weight":0.8},
"Kneecops, plate":{"price":75,"weight":2.4},              
"Rerebraces, kurbul":{"price":30,"weight":1.5},
"Rerebraces, plate":{"price":150,"weight":4.8},
"Vambraces, kurbul":{"price":25,"weight":1.3},
"Vambraces, plate":{"price":125,"weight":4.0},
