
/**
 * House rule tables
 * These tables will override attributes from cannon
 */

const houserule_tables = {
    default_abilities: {
        "Atk":`!attack @{selected|token_id} ?{aim zone|mid|high|low|arms|legs|torso|head|neck|skull|abdomen|face|thorax|shoulder|hip|thigh|knee|calf|foot|upper_arm|elbow|forearm|hand|groin} ?{Aspect|H|B|E|P|F} ?{Attack Type|melee|missle} ?{Mod|0} @{target|token_id} %{@{character_name}|helper-Weapons}`,
        "Fumble":"&{template:check-lt} {{character_name=@{selected|token_name}}} {{rolldesc=rolls Fumble}} {{rolltarget=[[@{COMBAT_DEX}]]}} {{rollresult=[[[[3d6]] + @{selected|bar3} + @{ENCUMBRANCE}]]}} {{base=@{COMBAT_DEX}}} {{rolltype=3d6+[[@{selected|bar3} + @{ENCUMBRANCE}]]}} {{penalty=[[0]]}}",
        "Stumble":"&{template:check-lt} {{character_name=@{selected|token_name}}} {{rolldesc=rolls Stumble}} {{rolltarget=[[@{COMBAT_AGL}]]}} {{rollresult=[[[[3d6]] + @{selected|bar3} + @{ENCUMBRANCE}]]}} {{base=@{COMBAT_AGL}}} {{rolltype=3d6+[[@{selected|bar3} + @{ENCUMBRANCE}]]}} {{penalty=[[0]]}}",
        "ImproveSkill":"!improveskill @{character_id} %{@{character_name}|helper-SkillList}"
    },
    sheet_attack: {
        "re_syntax": /^(!(sheet)?attack|!attack) [-_a-zA-Z0-9]{20} mid|high|low|arms|legs|torso|head|neck|skull|abdomen|face|thorax|shoulder|hip|thigh|knee|calf|foot|upper_arm|elbow|forearm|hand|groin (H|B|E|P|F) (melee|missile) [-+]?[0-9]+ [-_a-zA-Z0-9]{20} .+$/,
        "hr_syntax": `![sheet]attack attacker_id mid|high|low|arms|legs|torso|head|neck|skull|abdomen|face|thorax|shoulder|hip|thigh|knee|calf|foot|upper_arm|elbow|forearm|hand|groin (H|B|E|P|F) (missile|melee) modifier defender_id weapon`    
    },
    skilllist: {
        "Acrobatics": { "type": "PHYSICAL", "sba": ["STR", "AGL", "AGL"], "ssm": { "Nad": "2", "Hir": "1" }, "oml": "2", "notes": "Trapeze, Tumbling, Vaulting, etc." },
        "CLIMBING": { "type": "PHYSICAL", "sba": ["STR", "DEX", "AGL"], "ssm": { "Ula": "2", "Ara": "2" }, "oml": "4", "notes": "None." },
        "CONDITION": { "type": "PHYSICAL", "sba": ["STR", "STA", "WIL"], "ssm": { "Ula": "1", "Lad": "1" }, "oml": "5", "notes": "None." },
        "Dancing": { "type": "PHYSICAL", "sba": ["DEX", "AGL", "AGL"], "ssm": { "Tar": "2", "Hir": "1", "Tai": "1" }, "oml": "2", "notes": "Different styles may be specialties." },
        "DODGE": { "type": "PHYSICAL", "sba": ["AGL", "AGL", "AGL"], "ssm": {}, "oml": "5", "notes": "Different styles may be specialties." },
        "JUMPING": { "type": "PHYSICAL", "sba": ["STR", "AGL", "AGL"], "ssm": { "Nad": "2", "Hir": "2" }, "oml": "4", "notes": "High Jump, Long Jump." },
        "Legerdemain": { "type": "PHYSICAL", "sba": ["DEX", "DEX", "WIL"], "ssm": { "Sko": "2", "Tai": "2", "Tar": "2" }, "oml": "1", "notes": "Pursecutting, Conjuring, etc." },
        "Searching": { "type": "PHYSICAL", "sba": ["DEX", "EYE", "INT"], "ssm": {}, "oml": "2", "notes": "Used to find hidden or secret doors or things." },
        "Skiing": { "type": "PHYSICAL", "sba": ["STR", "DEX", "AGL"], "ssm": { "Mas": "2", "Sko": "1", "Lad": "1" }, "oml": "1", "notes": "None." },
        "STEALTH": { "type": "PHYSICAL", "sba": ["AGL", "HRG", "WIL"], "ssm": { "Hir": "2", "Tar": "2", "Tai": "2" }, "oml": "3", "notes": "None." },
        "Swimming": { "type": "PHYSICAL", "sba": ["STA", "DEX", "AGL"], "ssm": { "Sko": "1", "Mas": "3", "Lad": "3" }, "oml": "1", "notes": "None." },
        "THROWING": { "type": "PHYSICAL", "sba": ["STR", "DEX", "EYE"], "ssm": { "Hir": "2", "Tar": "1", "Nad": "1" }, "oml": "4", "notes": "None." },
        "Acting": { "type": "COMMUNICATION", "sba": ["AGL", "VOI", "INT"], "ssm": { "Tar": "1", "Tai": "1" }, "oml": "2", "notes": "None." },
        "AWARENESS": { "type": "COMMUNICATION", "sba": ["EYE", "HRG", "SML"], "ssm": { "Hir": "2", "Tar": "2" }, "oml": "4", "notes": "None." },
        "INTRIGUE": { "type": "COMMUNICATION", "sba": ["INT", "AUR", "WIL"], "ssm": { "Tai": "1", "Tar": "1", "Sko": "1" }, "oml": "3", "notes": "None." },
        "Lovecraft": { "type": "COMMUNICATION", "sba": ["CML", "AGL", "VOI"], "ssm": { "Mas": "1", "Ang": "1" }, "oml": "3", "notes": "GM Discretion." },
        "MentalConflict": { "type": "COMMUNICATION", "sba": ["AUR", "WIL", "WIL"], "ssm": {}, "oml": "3", "notes": "None." },
        "Musician": { "type": "COMMUNICATION", "sba": ["DEX", "HRG", "HRG"], "ssm": { "Mas": "1", "Ang": "1" }, "oml": "1", "notes": "Each instrument is a separate skill." },
        "ORATORY": { "type": "COMMUNICATION", "sba": ["CML", "VOI", "INT"], "ssm": { "Tar": "1" }, "oml": "2", "notes": "None." },
        "RHETORIC": { "type": "COMMUNICATION", "sba": ["VOI", "INT", "WIL"], "ssm": { "Tai": "1", "Tar": "1", "Sko": "1" }, "oml": "3", "notes": "Command, Diplomacy, Intimidation." },
        "SINGING": { "type": "COMMUNICATION", "sba": ["HRG", "VOI", "VOI"], "ssm": { "Mas": "1" }, "oml": "3", "notes": "Different styles may be specialties." },
        "Tactics": { "type": "COMMUNICATION", "sba": ["INT", "INT", "WIL"], "ssm": {}, "oml": "1", "notes": "Small unit tactics successful roll gives advantages in skirmish." },
        "Language": { "type": "COMMUNICATION", "sba": ["VOI", "INT", "WIL"], "ssm": { "Tai": "1" }, "oml": "5", "notes": "11 Each Language is a separate skill." },
        "Script": { "type": "COMMUNICATION", "sba": ["DEX", "EYE", "INT"], "ssm": { "Tar": "1", "Tai": "1" }, "oml": "6", "notes": "Each Script is a separate skill" },
        "Agrik": { "type": "RITUAL", "sba": ["VOI", "INT", "STR"], "ssm": { "Nad": "2", "Ang": "1", "Ahn": "1" }, "oml": "1", "notes": "Liturgy, Theology, Scriptor" },
        "Halea": { "type": "RITUAL", "sba": ["VOI", "INT", "CML"], "ssm": { "Tar": "2", "Hir": "1", "Mas": "1" }, "oml": "1", "notes": "Liturgy, Theology, Scriptor" },
        "Ilvir": { "type": "RITUAL", "sba": ["VOI", "INT", "AUR"], "ssm": { "Sko": "2", "Tai": "1", "Ula": "1" }, "oml": "1", "notes": "Liturgy, Theology, Scriptor" },
        "Larani": { "type": "RITUAL", "sba": ["VOI", "INT", "WIL"], "ssm": { "Ang": "2", "Ahn": "1", "Fen": "1" }, "oml": "1", "notes": "Liturgy, Theology, Scriptor" },
        "Morgath": { "type": "RITUAL", "sba": ["VOI", "INT", "AUR"], "ssm": { "Lad": "2", "Ahn": "1", "Mas": "1" }, "oml": "1", "notes": "Liturgy, Theology, Scriptor" },
        "Naveh": { "type": "RITUAL", "sba": ["VOI", "INT", "WIL"], "ssm": { "Mas": "2", "Sko": "1", "Tar": "1" }, "oml": "1", "notes": "Liturgy, Theology, Scriptor" },
        "Peoni": { "type": "RITUAL", "sba": ["VOI", "INT", "DEX"], "ssm": { "Ara": "2", "Ang": "1", "Ula": "1" }, "oml": "1", "notes": "Liturgy, Theology, Scriptor" },
        "Sarajin": { "type": "RITUAL", "sba": ["VOI", "INT", "STR"], "ssm": { "Fen": "2", "Ara": "1", "Lad": "1" }, "oml": "1", "notes": "Liturgy, Theology, Scriptor" },
        "Save-Knor": { "type": "RITUAL", "sba": ["VOI", "INT", "INT"], "ssm": { "Tai": "2", "Sko": "1", "Tar": "1" }, "oml": "1", "notes": "Liturgy, Theology, Scriptor" },
        "Siem": { "type": "RITUAL", "sba": ["VOI", "INT", "AUR"], "ssm": { "Hir": "2", "Fen": "1", "Ula": "1" }, "oml": "1", "notes": "Liturgy, Theology, Scriptor" },
        "INITIATIVE": { "type": "COMBAT", "sba": ["AGL", "WIL", "WIL"], "ssm": {}, "oml": "4", "notes": "None." },
        "UNARMED": { "type": "COMBAT", "sba": ["STR", "DEX", "AGL"], "ssm": { "Ang": "2", "Mas": "2", "Lad": "2", "Ula": "2" }, "oml": "4", "notes": "Brawling, Wrestling, Martial Arts." },
        "Riding": { "type": "COMBAT", "sba": ["DEX", "AGL", "WIL"], "ssm": { "Ula": "1", "Ara": "1" }, "oml": "1", "notes": "Always averaged with Steed Initiative." },
        "RIDING": { "type": "COMBAT", "sba": ["DEX", "AGL", "WIL"], "ssm": { "Ula": "1", "Ara": "1" }, "oml": "1", "notes": "Always averaged with Steed Initiative." },
        "Axe": { "type": "COMBAT", "sba": ["STR", "STR", "DEX"], "ssm": { "Ahn": "1", "Fen": "1", "Ang": "1" }, "oml": "3", "notes": "Battleaxe, Handaxe, Shorkana, Pickaxe, Sickle, Warhammer." },
        "Blowgun": { "type": "COMBAT", "sba": ["STA", "DEX", "EYE"], "ssm": { "Hir": "2", "Tar": "1", "Nad": "1" }, "oml": "4", "notes": "None." },
        "Bow": { "type": "COMBAT", "sba": ["STR", "DEX", "EYE"], "ssm": { "Hir": "1", "Tar": "1", "Nad": "1" }, "oml": "2", "notes": "Crossbow, Hartbow, Longbow, Shortbow." },
        "Club": { "type": "COMBAT", "sba": ["STR", "STR", "DEX"], "ssm": { "Ula": "1", "Ara": "1" }, "oml": "4", "notes": "Club, Mace, Maul, Morningstar." },
        "Dagger": { "type": "COMBAT", "sba": ["DEX", "DEX", "EYE"], "ssm": { "Ang": "2", "Nad": "2" }, "oml": "3", "notes": "Dagger, Keltan, Knife, Taburi." },
        "Flail": { "type": "COMBAT", "sba": ["DEX", "DEX", "DEX"], "ssm": { "Hir": "1", "Tar": "1", "Nad": "1" }, "oml": "1", "notes": "Ball & Chain, Grainflail, Nachakas, Warflail." },
        "Net": { "type": "COMBAT", "sba": ["DEX", "DEX", "EYE"], "ssm": { "Mas": "1", "Sko": "1", "Lad": "1" }, "oml": "1", "notes": "Cloak, Net, etc." },
        "Polearm": { "type": "COMBAT", "sba": ["STR", "STR", "DEX"], "ssm": { "Ang": "1", "Ara": "1" }, "oml": "2", "notes": "Lance, Glaive/Bill, Jousting Pole, Pike, Poleaxe." },
        "Shield": { "type": "COMBAT", "sba": ["STR", "DEX", "DEX"], "ssm": { "Ula": "1", "Lad": "1", "Mas": "1" }, "oml": "3", "notes": "Buckler, Kite, Knight, Round, Tower shields." },
        "Sling": { "type": "COMBAT", "sba": ["DEX", "DEX", "EYE"], "ssm": { "Hir": "1", "Tar": "1", "Nad": "1" }, "oml": "1", "notes": "Sling, Staffsling." },
        "Spear": { "type": "COMBAT", "sba": ["STR", "STR", "DEX"], "ssm": { "Ara": "1", "Fen": "1", "Ula": "1" }, "oml": "3", "notes": "Javelin, Staff, Trident." },
        "Sword": { "type": "COMBAT", "sba": ["STR", "DEX", "DEX"], "ssm": { "Ang": "3", "Ahn": "1", "Nad": "1" }, "oml": "3", "notes": "Bastard Sword, Battlesword, Broadsword, Estoc, Falchion, Longknife, Mang, Mankar, Shortsword." },
        "Whip": { "type": "COMBAT", "sba": ["DEX", "DEX", "EYE"], "ssm": { "Hir": "1", "Nad": "1" }, "oml": "1", "notes": "Isagra, Whip." },
        "Agriculture": { "type": "LORE", "sba": ["STR", "STA", "WIL"], "ssm": { "Ula": "2", "Ara": "2" }, "oml": "2", "notes": "Different crops may be specialties." },
        "Alchemy": { "type": "LORE", "sba": ["SML", "INT", "AUR"], "ssm": { "Sko": "3", "Tai": "2", "Mas": "2" }, "oml": "1", "notes": "Different techniques may be specialties." },
        "Animalcraft": { "type": "LORE", "sba": ["AGL", "VOI", "WIL"], "ssm": { "Ula": "1", "Ara": "1" }, "oml": "1", "notes": "Horsecraft, Oxcraft, Birdcraft, etc." },
        "Astrology": { "type": "LORE", "sba": ["EYE", "INT", "AUR"], "ssm": { "Tar": "1" }, "oml": "1", "notes": "Astromancy, Astronomy." },
        "Brewing": { "type": "LORE", "sba": ["DEX", "SML", "SML"], "ssm": { "Sko": "3", "Tai": "2", "Mas": "2" }, "oml": "2", "notes": "Different beverage types may be specialties." },
        "Ceramics": { "type": "LORE", "sba": ["DEX", "DEX", "EYE"], "ssm": { "Ula": "2", "Ara": "2" }, "oml": "2", "notes": "Different artistic styles may be specialties." },
        "Cookery": { "type": "LORE", "sba": ["DEX", "SML", "SML"], "ssm": { "Sko": "1" }, "oml": "3", "notes": "Cultural, religious, and regional specialties." },
        "Drawing": { "type": "LORE", "sba": ["DEX", "EYE", "EYE"], "ssm": { "Sko": "1", "Tai": "1" }, "oml": "2", "notes": "Cartography, Painting, Sketching, etc." },
        "Driving": { "type": "LORE", "sba": ["DEX", "AGL", "WIL"], "ssm": { "Ula": "1", "Ara": "1" }, "oml": "1", "notes": "Must specialize wagon or cart." },
        "Embalming": { "type": "LORE", "sba": ["DEX", "EYE", "SML"], "ssm": { "Sko": "1", "Ula": "1" }, "oml": "1", "notes": "Cultural, religious, and regional specialties." },
        "Engineering": { "type": "LORE", "sba": ["DEX", "INT", "INT"], "ssm": { "Ula": "2", "Ara": "2", "Fen": "1" }, "oml": "1", "notes": "Fortifications, Mills, Siege Engines, etc" },
        "Fishing": { "type": "LORE", "sba": ["DEX", "EYE", "WIL"], "ssm": { "Mas": "2", "Lad": "2" }, "oml": "3", "notes": "Different techniques may be specialties." },
        "Hidework": { "type": "LORE", "sba": ["DEX", "DEX", "EYE"], "ssm": { "Hir": "2", "Tar": "1", "Nad": "1" }, "oml": "1", "notes": "Bowyer, Fletcher." },
        "Folklore": { "type": "LORE", "sba": ["VOI", "INT", "INT"], "ssm": { "Tai": "2" }, "oml": "3", "notes": "Cultural and/or regional specialties." },
        "Foraging": { "type": "LORE", "sba": ["DEX", "SML", "INT"], "ssm": { "Ula": "2", "Ara": "2" }, "oml": "3", "notes": "Different climate/terrain types may be specialties." },
        "Glasswork": { "type": "LORE", "sba": ["DEX", "EYE", "WIL"], "ssm": { "Fen": "2" }, "oml": "1", "notes": "Different styles may be specialties." },
        "Heraldry": { "type": "LORE", "sba": ["DEX", "EYE", "WIL"], "ssm": { "Sko": "1", "Tai": "1" }, "oml": "1", "notes": "Cultural and/or regional specialties." },
        "Herblore": { "type": "LORE", "sba": ["EYE", "SML", "INT"], "ssm": { "Ula": "3", "Ara": "2" }, "oml": "1", "notes": "Different climate/terrain types may be specialties." },
        "Hidework": { "type": "LORE", "sba": ["DEX", "SML", "WIL"], "ssm": { "Ula": "1", "Ara": "1" }, "oml": "2", "notes": "Tanning, Parchment, Taxidermy, Leatherworking, etc." },
        "Jewelcraft": { "type": "LORE", "sba": ["DEX", "EYE", "WIL"], "ssm": { "Fen": "3", "Tar": "1", "Ara": "1" }, "oml": "1", "notes": "Goldsmith, Silversmith, Gemcutter, Designer, etc." },
        "Law": { "type": "LORE", "sba": ["VOI", "INT", "WIL"], "ssm": { "Tar": "1", "Tai": "1" }, "oml": "1", "notes": "Cultural and/or regional specialties." },
        "Lockcraft": { "type": "LORE", "sba": ["DEX", "EYE", "WIL"], "ssm": { "Fen": "1" }, "oml": "1", "notes": "Lockmaker, Lockpicker, Fine Mechanician, etc." },
        "Masonry": { "type": "LORE", "sba": ["STR", "DEX", "INT"], "ssm": { "Ula": "2", "Ara": "2" }, "oml": "1", "notes": "Architect, Builder, Stonecutter, Sculptor, etc." },
        "Mathematics": { "type": "LORE", "sba": ["INT", "INT", "WIL"], "ssm": { "Tai": "3", "Tar": "1", "Sko": "1" }, "oml": "1", "notes": "Algebra, Bookkeeping, Geometry, etc." },
        "Metalcraft": { "type": "LORE", "sba": ["STR", "DEX", "WIL"], "ssm": { "Fen": "3", "Ahn": "1", "Ang": "1" }, "oml": "1", "notes": "Different metal types (Tinsmith, Coppersmith, etc.)." },
        "Milling": { "type": "LORE", "sba": ["STR", "DEX", "SML"], "ssm": { "Ula": "1" }, "oml": "2", "notes": "Baking, Milling." },
        "Mining": { "type": "LORE", "sba": ["STR", "EYE", "INT"], "ssm": { "Ula": "2", "Ara": "2", "Fen": "1" }, "oml": "1", "notes": "Different mineral/metal types." },
        "Needlework": { "type": "LORE", "sba": ["DEX", "EYE", "WIL"], "ssm": { "Ula": "0" }, "oml": "1", "notes": "" },
        "Packing": { "type": "LORE", "sba": ["DEX", "EYE", "INT"], "ssm": { "Fen": "1", "Ula": "2", "Ara": "2" }, "oml": "1", "notes": "Pack to maximize available space and knot tying." },
        "Perfumery": { "type": "LORE", "sba": ["SML", "SML", "INT"], "ssm": { "Hir": "1", "Sko": "1", "Tar": "1" }, "oml": "1", "notes": "Incense, Scented Oils, Soap, etc." },
        "Physician": { "type": "LORE", "sba": ["DEX", "EYE", "INT"], "ssm": { "Mas": "2", "Sko": "1", "Tai": "1" }, "oml": "1", "notes": "Homeopathy, Surgery, etc." },
        "PHYSICIAN": { "type": "LORE", "sba": ["DEX", "EYE", "INT"], "ssm": { "Mas": "2", "Sko": "1", "Tai": "1" }, "oml": "1", "notes": "Homeopathy, Surgery, etc." },
        "Piloting": { "type": "LORE", "sba": ["DEX", "EYE", "INT"], "ssm": { "Lad": "3", "Mas": "1" }, "oml": "1", "notes": "Navigation, Sailing, Specific Waterways, etc." },
        "Runecraft": { "type": "LORE", "sba": ["INT", "AUR", "AUR"], "ssm": { "Tai": "2", "Sko": "1" }, "oml": "1", "notes": "Regional styles may be specialties." },
        "Seamanship": { "type": "LORE", "sba": ["STR", "DEX", "AGL"], "ssm": { "Lad": "3", "Mas": "1", "Sko": "1" }, "oml": "2", "notes": "Rowing, Sailing (small boats), Sculling." },
        "Shipwright": { "type": "LORE", "sba": ["STR", "DEX", "INT"], "ssm": { "Lad": "3", "Mas": "1" }, "oml": "1", "notes": "Naval Architecture, Sailmaking, etc." },
        "Survival": { "type": "LORE", "sba": ["STR", "DEX", "INT"], "ssm": { "Ula": "2", "Ara": "1" }, "oml": "3", "notes": "Different climate/terrain types may be specialties." },
        "Tarotry": { "type": "LORE", "sba": ["INT", "AUR", "WIL"], "ssm": { "Tar": "2", "Tai": "2", "Sko": "1", "Hir": "1" }, "oml": "1", "notes": "Regional styles may be specialties." },
        "Textilecraft": { "type": "LORE", "sba": ["DEX", "DEX", "EYE"], "ssm": { "Ula": "1", "Ara": "1" }, "oml": "2", "notes": "Embroidery, Needlework, Tailoring, Weaving, etc." },
        "Timbercraft": { "type": "LORE", "sba": ["STR", "DEX", "AGL"], "ssm": { "Ula": "3", "Ara": "1" }, "oml": "2", "notes": "Cutting, Felling, Tree Care, etc." },
        "Tracking": { "type": "LORE", "sba": ["EYE", "SML", "WIL"], "ssm": { "Ula": "3", "Ara": "3" }, "oml": "2", "notes": "Specialist for any race or creature type." },
        "Trap/Hunt": { "type": "LORE", "sba": ["EYE", "SML", "WIL"], "ssm": { "Ula": "3", "Ara": "3" }, "oml": "1", "notes": "Specialist for any race or creature type." },
        "Weaponcraft": { "type": "LORE", "sba": ["STR", "DEX", "WIL"], "ssm": { "Fen": "3", "Ahn": "1", "Ang": "1" }, "oml": "1", "notes": "Weapon or Armour group (eg. Swords or Mailcraft)." },
        "Weatherlore": { "type": "LORE", "sba": ["INT", "EYE", "SML"], "ssm": { "Hir": "1", "Tar": "1", "Mas": "1", "Lad": "1" }, "oml": "3", "notes": "Different climate types may be specialties." },
        "Woodcraft": { "type": "LORE", "sba": ["DEX", "DEX", "WIL"], "ssm": { "Ula": "2", "Ara": "1", "Lad": "1" }, "oml": "2", "notes": "Cabinetry, Carpentry, Cooper, Carving, Wheelwright." },
        "Lyahvi": { "type": "MAGIC", "sba": ["AUR", "AUR", "EYE"], "ssm": { "Ula": "-3", "Ara": "-2", "Fen": "-1", "Ang": "1", "Nad": "2", "Nir": "3", "Tar": "2", "Tai": "1", "Mas": "-1", "Lad": "-2" }, "oml": "1", "notes": "none" },
        "Peleahn": { "type": "MAGIC", "sba": ["AUR", "AUR", "AGL"], "ssm": { "Ula": "-1", "Fen": "1", "Ahn": "2", "Ang": "3", "Nad": "2", "Nir": "1", "Tai": "-1", "Sko": "-2", "Mas": "-3", "Lad": "-2" }, "oml": "1", "notes": "none" },
        "Jmorvi": { "type": "MAGIC", "sba": ["AUR", "AUR", "STR"], "ssm": { "Ula": "1", "Ara": "2", "Fen": "3", "Ahn": "2", "Ang": "1", "Nir": "-1", "Tar": "-2", "Tai": "-3", "Sko": "-2", "Mas": "-1" }, "oml": "1", "notes": "none" },
        "Fyvria": { "type": "MAGIC", "sba": ["AUR", "AUR", "SML"], "ssm": { "Ula": "3", "Ara": "2", "Fen": "1", "Ang": "-1", "Nad": "-2", "Hir": "-3", "Tar": "-2", "Tai": "-1", "Mas": "1", "Lad": "2" }, "oml": "1", "notes": "none" },
        "Odivshe": { "type": "MAGIC", "sba": ["AUR", "AUR", "DEX"], "ssm": { "Ula": "1", "Fen": "-1", "Ahn": "-2", "Ang": "-3", "Nad": "-2", "Hir": "-1", "Tai": "1", "Sko": "2", "Mas": "3", "Lad": "2" }, "oml": "1", "notes": "none" },
        "Savorya": { "type": "MAGIC", "sba": ["AUR", "AUR", "INT"], "ssm": { "Ula": "-1", "Ara": "-2", "Fen": "-3", "Ahn": "-2", "Ang": "-1", "Hir": "1", "Tar": "2", "Tai": "3", "Sko": "2", "Mas": "1" }, "oml": "1", "notes": "none" },
        "Neutral": { "type": "MAGIC", "sba": ["AUR", "AUR", "WIL"], "ssm": { "Ula": "0" }, "oml": "1", "notes": "none" }
    },
    prices: {
        "Skull, bone": { "price": 0, "weight": 0 },
        "Halfhelm, kurbul": { "price": 20, "weight": 1.0 },
        "Halfhelm, ring": { "price": 28, "weight": 1.0 },
        "Halfhelm, plate": { "price": 100, "weight": 3.2 },
        "Three-quarter helm, plate": { "price": 175, "weight": 5.6 },
        "Greathelm, plate": { "price": 275, "weight": 8.8 },
        "Boots, knee, cloth": { "price": 44, "weight": 2.8 },
        "Boots, knee, leather": { "price": 76, "weight": 3.8 },
        "Boots, calf, cloth": { "price": 38, "weight": 2.2 },
        "Boots, calf, leather": { "price": 64, "weight": 3.2 },
        "Breastplate, kurbul": { "price": 60, "weight": 3.0 },
        "Backplate, kurbul": { "price": 60, "weight": 3.0 },
        "Cuirass, kurbul": { "price": 120, "weight": 6.0 },
        "Breastplate, plate": { "price": 300, "weight": 9.6 },
        "Backplate, plate": { "price": 300, "weight": 9.6 },
        "Cuirass, plate": { "price": 600, "weight": 19.2 },
        "Byrnie, ring": { "price": 308, "weight": 17.6 },
        "Byrnie, mail": { "price": 660, "weight": 22.0 },
        "Byrnie, scale": { "price": 440, "weight": 30.8 },
        "Byrnie(long), ring": { "price": 365, "weight": 19.6 },
        "Byrnie(long), mail": { "price": 760, "weight": 26.0 },
        "Byrnie(long), scale": { "price": 500, "weight": 34.8 },
        "Cap, cloth": { "price": 8, "weight": 0.4 },
        "Cap, leather": { "price": 16, "weight": 0.8 },
        "Cap, quilt": { "price": 16, "weight": 1.2 },
        "Cloak, cloth": { "price": 100, "weight": 6.6 },
        "Cloak, leather": { "price": 134, "weight": 9 },
        "Cloak, hood, cloth": { "price": 115, "weight": 8.6 },
        "Cloak, hood, leather": { "price": 140, "weight": 11 },
        "Cloak(long), cloth": { "price": 120, "weight": 8.8 },
        "Cloak(long), leather": { "price": 150, "weight": 12.0 },
        "Cloak(long), hood, cloth": { "price": 140, "weight": 10.8 },
        "Cloak(long), hood, leather": { "price": 170, "weight": 14.0 },
        "Cowl, cloth": { "price": 10, "weight": 0.8 },
        "Cowl, leather": { "price": 12, "weight": 1.6 },
        "Cowl, quilt": { "price": 32, "weight": 2.4 },
        "Cowl, mail": { "price": 120, "weight": 4.0 },
        "Cowl(long), cloth": { "price": 15, "weight": 1.2 },
        "Cowl(long), leather": { "price": 18, "weight": 2.4 },
        "Cowl(long), quilt": { "price": 42, "weight": 3.6 },
        "Cowl(long), mail": { "price": 180, "weight": 6.0 },
        "Dress(shortsleeve), cloth": { "price": 150, "weight": 7.8 },
        "Dress(longsleeve), cloth": { "price": 160, "weight": 8.2 },
        "Gambeson, quilt": { "price": 200, "weight": 19.5 },
        "Gloves, cloth": { "price": 15, "weight": 0.4 },
        "Gauntlets, leather": { "price": 16, "weight": 0.8 },
        "Gauntlets, ring": { "price": 28, "weight": 1.6 },
        "Mittens, mail": { "price": 60, "weight": 2.0 },
        "Hat, cloth": { "price": 16, "weight": 0.5 },
        "Hat, leather": { "price": 28, "weight": 1.2 },
        "Hauberk, ring": { "price": 420, "weight": 26 },
        "Hauberk, mail": { "price": 900, "weight": 27.0 },
        "Hauberk, scale": { "price": 600, "weight": 50 },
        "Hauberk(shortsleeve), ring": { "price": 399, "weight": 24 },
        "Hauberk(shortsleeve), mail": { "price": 855, "weight": 26.0 },
        "Hauberk(shortsleeve), scale": { "price": 570, "weight": 45.5 },
        "Hood, cloth": { "price": 16, "weight": 0.8 },
        "Hood, leather": { "price": 12, "weight": 1.6 },
        "Hood, quilt": { "price": 32, "weight": 2.4 },
        "Leggings, cloth": { "price": 88, "weight": 4.4 },
        "Leggings, leather": { "price": 176, "weight": 8.8 },
        "Leggings, quilt": { "price": 184, "weight": 9.2 },
        "Leggings, ring": { "price": 308, "weight": 17.6 },
        "Leggings, mail": { "price": 615, "weight": 22.0 },
        "Loincloth, cloth": { "price": 20, "weight": 1.0 },
        "Loincloth, leather": { "price": 40, "weight": 2.0 },
        "Loincloth, fur": { "price": 40, "weight": 2.4 },
        "Pants, cloth": { "price": 100, "weight": 4.0 },
        "Pants, leather": { "price": 165, "weight": 7.0 },
        "Pants, quilt": { "price": 174, "weight": 8.2 },
        "Pants, ring": { "price": 280, "weight": 16.4 },
        "Pants, mail": { "price": 184, "weight": 20.5 },
        "Robe, cloth": { "price": 156, "weight": 7.8 },
        "Robe, hood, cloth": { "price": 156, "weight": 7.8 },
        "Sandals, leather": { "price": 8, "weight": 1 },
        "Shirt, cloth": { "price": 100, "weight": 5.2 },
        "Shirt, leather": { "price": 120, "weight": 9.8 },
        "Shirt, quilt": { "price": 200, "weight": 15.0 },
        "Shirt(long), cloth": { "price": 100, "weight": 6.8 },
        "Shirt(long), leather": { "price": 120, "weight": 11.8 },
        "Shirt(long), quilt": { "price": 200, "weight": 17.5 },
        "Shoes, cloth ": { "price": 12, "weight": 1 },
        "Shoes, leather": { "price": 24, "weight": 1.2 },
        "Shorts, cloth": { "price": 40, "weight": 2.0 },
        "Shorts, leather": { "price": 60, "weight": 4.0 },
        "Shorts, fur": { "price": 60, "weight": 4.8 },
        "Skirt(mini), cloth": { "price": 20, "weight": 1.0 },
        "Skirt(mini), leather": { "price": 30, "weight": 1.4 },
        "Skirt(short), cloth": { "price": 20, "weight": 2.0 },
        "Skirt(short), leather": { "price": 30, "weight": 2.8 },
        "Skirt(mid), cloth": { "price": 20, "weight": 3.0 },
        "Skirt(mid), leather": { "price": 30, "weight": 4.2 },
        "Skirt(long), cloth": { "price": 20, "weight": 4.0 },
        "Skirt(long), leather": { "price": 30, "weight": 5.6 },
        "Surcoat, cloth": { "price": 104, "weight": 5.2 },
        "Surcoat, leather": { "price": 208, "weight": 10.4 },
        "Tunic, cloth": { "price": 88, "weight": 4.4 },
        "Tunic, leather": { "price": 114, "weight": 8.8 },
        "Tunic, quilt": { "price": 176, "weight": 13.2 },
        "Tunic(long), cloth": { "price": 100, "weight": 4.8 },
        "Tunic(long), leather": { "price": 125, "weight": 9.2 },
        "Tunic(long), quilt": { "price": 200, "weight": 15.6 },
        "Vest, cloth": { "price": 56, "weight": 2.8 },
        "Vest, leather": { "price": 112, "weight": 5.6 },
        "Vest, fur": { "price": 112, "weight": 7.0 },
        "Vest, quilt": { "price": 112, "weight": 7.0 },
        "Vest, scale": { "price": 280, "weight": 19.6 },
        "Ailettes, kurbul": { "price": 20, "weight": 1.0 },
        "Ailettes, plate": { "price": 100, "weight": 3.2 },
        "Coudes, kurbul": { "price": 10, "weight": 0.5 },
        "Coudes, plate": { "price": 50, "weight": 1.6 },
        "Gorget, kurbul": { "price": 5, "weight": 0.5 },
        "Gorget, plate": { "price": 50, "weight": 2.0 },
        "Greaves, kurbul": { "price": 50, "weight": 2.5 },
        "Greaves, plate": { "price": 250, "weight": 8.8 },
        "Kneecops, kurbul": { "price": 15, "weight": 0.8 },
        "Kneecops, plate": { "price": 75, "weight": 2.4 },
        "Rerebraces, kurbul": { "price": 30, "weight": 1.5 },
        "Rerebraces, plate": { "price": 150, "weight": 4.8 },
        "Vambraces, kurbul": { "price": 25, "weight": 1.3 },
        "Vambraces, plate": { "price": 125, "weight": 4.0 },
        "Axe, wood handle": { "price": 12, "weight": 3 },
        "Hatchet": { "price": 6, "weight": 1 },
        "Hoe": { "price": 3, "weight": 2 },
        "Iron, branding": { "price": 18, "weight": 5 },
        "Pick": { "price": 8, "weight": 5 },
        "Pitchfork": { "price": 6, "weight": 3 },
        "Saw, hack": { "price": 10, "weight": 2 },
        "Scythe": { "price": 24, "weight": 6 },
        "Spade": { "price": 8, "weight": 5 },
        "Ladder, 20'": { "price": 15, "weight": 30 },
        "Runestones, Set": { "price": 40, "weight": 2 },
        "Tankard, wood": { "price": 2, "weight": 0.25 },
        "Tankard, pewter": { "price": 4, "weight": 0.25 },
        "Spoon, wood": { "price": 2, "weight": 0.1 },
        "Spoon, pewter": { "price": 4, "weight": 0.1 },
        "Flint & steel": { "price": 2, "weight": 0.1 },
        "Tinderbox": { "price": 6, "weight": 0.5 },
        "Torch": { "price": 1, "weight": 0.5 },
        "Comb, wood": { "price": 2, "weight": 0.1 },
        "Comb, ivory": { "price": 20, "weight": 0.1 },
        "Bell, hand": { "price": 5, "weight": 0.2 },
        "Brush, hair": { "price": 3, "weight": 0.2 },
        "Backbag, small, canvas": { "price": 4, "weight": 0.5 },
        "Backbag, medium, leather": { "price": 12, "weight": 1 },
        "Beltpouch, leather": { "price": 3, "weight": 0.5 },
        "Beltpouch, silk": { "price": 35, "weight": 0.2 },
        "Mirror, bronze": { "price": 12, "weight": 0.25 },
        "Mirror, silver": { "price": 300, "weight": 0.25 },
        "Beltpouch, leather": { "price": 3, "weight": 0.5 },
        "Beltpouch, buckram": { "price": 5, "weight": 0.25 },
        "Beltpouch, silk": { "price": 35, "weight": 0.25 },
        "Notebook": { "price": 50, "weight": 2.0 },
        "Alchemical Recipe book": { "price": 150, "weight": 5.0 },
        "Tarot Cards, deck": { "price": 75, "weight": 0.5 },
        "Wineskin, small": { "price": 6, "weight": 6 },
        "Papercase, leather": { "price": 180, "weight": 3 },
        "Pipe, smoking": { "price": 2, "weight": 0.1 },
        "Rope, hemp, light, 100'": { "price": 100, "weight": 5 },
        "Scale/balance": { "price": 72, "weight": 5 },
        "Vellum, 10 sheets": { "price": 20, "weight": 0.1 },
        "Pen, metal": { "price": 4, "weight": 0.1 },
        "Pen, quill": { "price": 1, "weight": 0.1 },
        "Inkwell, glass": { "price": 30, "weight": 0.5 },
        "Wax, sealing": { "price": 4, "weight": 0.2 },
        "Vial, glass": { "price": 24, "weight": 0.1 },
        "Jar, glass, large": { "price": 18, "weight": 1.0 },
        "Calf Hide": { "price": 16, "weight": 10 },
        "Lambskin": { "price": 3, "weight": 5 },
        "Sheep Hide": { "price": 4, "weight": 7 },
        "Cow Hide": { "price": 10, "weight": 20 },
        "Beaver Hide": { "price": 30, "weight": 5 },
        "Deer Hide": { "price": 6, "weight": 7 },
        "Lantern, metal": { "price": 12, "weight": 1 },
        "Flask of oil (metal)": { "price": 7, "weight": 1 },
        "Cage, wood, small": { "price": 7, "weight": 2 },
        "Textbook": { "price": 150, "weight": 3 },
        "Frankincense, oz, jar": { "price": 80, "weight": 0.25 },
        "Perfume, oz, bottle": { "price": 11, "weight": 0.25 },
        "Elprequir, 1 dose": { "price": 18, "weight": 0.1 },
        "Rasakile, 1 dose": { "price": 12, "weight": 0.1 },
        "Opiates, 1 oz": { "price": 106, "weight": 0.1 },
        "Doshenkana, 1 dose": { "price": 21, "weight": 0.1 },
        "Doshenkana, 10 doses": { "price": 175, "weight": 1.0 },
        "Net, 2 fathom": { "price": 120, "weight": 5 },
        "Fishhooks, dozen": { "price": 2, "weight": 0.1 },
        "Fishing line, 50'": { "price": 10, "weight": 0.5 },
        "Physician's Bag": { "price": 186, "weight": 10 },
        "Portable writing kit": { "price": 25, "weight": 5 },
        "Hideworking kit": { "price": 24, "weight": 5 },
        "Textilcraft kit": { "price": 24, "weight": 5 },
        "Woodcarving kit": { "price": 24, "weight": 5 },
        "Carpentry kit": { "price": 36, "weight": 10 },
        "Lockpick kit": { "price": 24, "weight": 1 },
        "Armor Repair kit": { "price": 24, "weight": 10 },
        "Mason's kit": { "price": 36, "weight": 15 },
        "Alchemist's kit": { "price": 72, "weight": 10 },
        "Camp cooking kit": { "price": 24, "weight": 5 },
        "Metalcrafter's kit": { "price": 24, "weight": 10 },
        "Lute": { "price": 200, "weight": 5 },
        "Lyre": { "price": 120, "weight": 5 },
        "Flute": { "price": 3, "weight": 0.5 },
        "Pipes": { "price": 60, "weight": 1 },
        "Recorder": { "price": 4, "weight": 0.5 },
        "Gittern": { "price": 150, "weight": 5 },
        "Harp": { "price": 300, "weight": 10 },
        "Tabol": { "price": 20, "weight": 2 },
        "Belt, leather": { "price": 10, "weight": 1 },
        "Holy Symbol, brass": { "price": 12, "weight": 0.1 },
        "Holy Symbol, iron": { "price": 18, "weight": 0.1 },
        "Holy Symbol, wood": { "price": 8, "weight": 0.1 },
        "Holy Symbol, silver": { "price": 32, "weight": 0.1 },
        "Holy Symbol, gold": { "price": 120, "weight": 0.1 },
        "Scabbard, dagger": { "price": 12, "weight": 0.5 },
        "Scabbard, sword": { "price": 48, "weight": 1 },
        "Scabbard, battlesword": { "price": 150, "weight": 3 },
        "Shield(Round)": { "price": 42, "weight": 6 },
        "Shield(Kite)": { "price": 72, "weight": 7 },
        "Shield(Knight)": { "price": 60, "weight": 5 },
        "Shield(Tower)": { "price": 96, "weight": 8 },
        "Shield(Buckler)": { "price": 24, "weight": 3 },
        "Dagger": { "price": 24, "weight": 1 },
        "Keltan": { "price": 36, "weight": 2 },
        "Knife": { "price": 6, "weight": 1 },
        "Taburi": { "price": 20, "weight": 1 },
        "Sword(Longknife)": { "price": 96, "weight": 1 },
        "Sword(Shortsword)": { "price": 90, "weight": 2 },
        "Sword(Broadsword)": { "price": 150, "weight": 3 },
        "Mang": { "price": 150, "weight": 3 },
        "Mankar": { "price": 150, "weight": 2 },
        "Sword(Falchion)": { "price": 120, "weight": 4 },
        "Sword(Bastard Sword)": { "price": 180, "weight": 5 },
        "Sword(Battlesword)": { "price": 230, "weight": 8 },
        "Club": { "price": 12, "weight": 3 },
        "Club(Mace)": { "price": 84, "weight": 4 },
        "Club(Morningstar)": { "price": 48, "weight": 5 },
        "Club(Maul)": { "price": 24, "weight": 7 },
        "Hatchet": { "price": 12, "weight": 2 },
        "Axe(Handaxe)": { "price": 72, "weight": 3 },
        "Axe(Warhammer)": { "price": 90, "weight": 5 },
        "Axe(Battleaxe)": { "price": 100, "weight": 6 },
        "Flail(Grainflail)": { "price": 12, "weight": 2 },
        "Flail(Ball & Chain)": { "price": 60, "weight": 4 },
        "Flail(Warflail)": { "price": 60, "weight": 5 },
        "Spear(Staff)": { "price": 36, "weight": 4 },
        "Spear(Javelin)": { "price": 48, "weight": 3 },
        "Spear(Spear)": { "price": 60, "weight": 5 },
        "Spear(Trident)": { "price": 72, "weight": 6 },
        "Polearm(Lance)": { "price": 120, "weight": 8 },
        "Polearm(Poleaxe)": { "price": 96, "weight": 8 },
        "Bow(Longbow)": { "price": 36, "weight": 3 },
        "Bow(Shortbow)": { "price": 24, "weight": 2 },
        "Bow(Hartbow)": { "price": 96, "weight": 2 },
        "Arrow, dozen": { "price": 15, "weight": 2 },
        "Quiver": { "price": 8, "weight": 1 },
        "Anklet, Bone/Horn": { "price": 3, "weight": 0.125 },
        "Anklet, Copper": { "price": 5, "weight": 0.125 },
        "Anklet, Gold with gem": { "price": 3000, "weight": 0.125 },
        "Anklet, Gold": { "price": 2400, "weight": 0.125 },
        "Anklet, Silver": { "price": 120, "weight": 0.125 },
        "Broach, Bone/Horn": { "price": 1, "weight": 0.03 },
        "Broach, Copper": { "price": 3, "weight": 0.03 },
        "Broach, Gold with gem": { "price": 1000, "weight": 0.03 },
        "Broach, Gold": { "price": 600, "weight": 0.03 },
        "Broach, Silver": { "price": 30, "weight": 0.03 },
        "Circlet, Bone/Horn": { "price": 10, "weight": 0.3125 },
        "Circlet, Copper": { "price": 20, "weight": 0.3125 },
        "Circlet, Gold with gem": { "price": 7000, "weight": 0.3125 },
        "Circlet, Gold": { "price": 6000, "weight": 0.3125 },
        "Circlet, Silver with gem": { "price": 600, "weight": 0.3125 },
        "Circlet, Silver": { "price": 300, "weight": 0.3125 },
        "Earing, Bone/Horn": { "price": 1, "weight": 0.01 },
        "Earing, Copper": { "price": 1, "weight": 0.01 },
        "Earing, Gold with gem": { "price": 425, "weight": 0.01 },
        "Earing, Gold": { "price": 225, "weight": 0.01 },
        "Earing, Silver": { "price": 15, "weight": 0.01 },
        "Necklace, Bone/Horn": { "price": 5, "weight": 0.25 },
        "Necklace, Copper": { "price": 8, "weight": 0.25 },
        "Necklace, Gold with gem": { "price": 6000, "weight": 0.25 },
        "Necklace, Gold": { "price": 4800, "weight": 0.25 },
        "Necklace, Silver": { "price": 240, "weight": 0.25 },
        "Pendant, Bone/Horn": { "price": 5, "weight": 0.05 },
        "Pendant, Copper": { "price": 8, "weight": 0.05 },
        "Pendant, Gold with gem": { "price": 1400, "weight": 0.05 },
        "Pendant, Gold": { "price": 900, "weight": 0.05 },
        "Pendant, Silver": { "price": 45, "weight": 0.05 },
        "Ring, Bone/Horn": { "price": 1, "weight": 0.03 },
        "Ring, Copper": { "price": 1, "weight": 0.03 },
        "Ring, Gold with gem": { "price": 900, "weight": 0.03 },
        "Ring, Gold": { "price": 600, "weight": 0.03 },
        "Ring, Silver": { "price": 30, "weight": 0.03 },
        "q1": { "price": 1, "weight": 1.0 },
        "Gold Crown": { "price": 320, "weight": .06 },
        "Pence": { "price": 1, "weight": .004 },
        "Lightsabre": { "price": 9600000, "weight": 0.2 },
        "Sword(StarSteel)": { "price": 150, "weight": 2 },
        "Bow(Crossbow)": { "price": 600, "weight": 5.0 },
        "Polearm(Pike)": { "price": 96, "weight": 12 },
        "Unarmed(Punch)": { "price": 0, "weight": 0 },
        "Unarmed(Kick)": { "price": 0, "weight": 0, },
        "Bow(Minicrossbow)": { "price": 1800, "weight": 2.5 }
    },
    occupational_skills: {
        "Alchemist": [
            "Alchemy/4",
            "Mathematics/3",
            "Herblore/3",
            "Mining/2",
            "Physician/2",
            "Script/5"
        ],
        "Animal Trainer": [
            "Animalcraft/4",
            "Hidework/2",
            "RIDING/2"
        ],
        "Apothecary": [
            "Herblore/4",
            "Alchemy/2",
            "Mathematics/2",
            "Physician/2",
            "Script/5"
        ],
        "Astrologer": [
            "Astrology/4",
            "Mathematics/3",
            "Drawing/3",
            "Tarotry/2",
            "Script/5"
        ],
        "Baliff": [
            "Law/3",
            "Agriculture/2",
            "INITIATIVE/6",
            "Foraging/4",
            "Survival/4",
            "Physician/2",
            "Heraldry/2",
            "Weaponcraft/2",
            "RIDING/6",
            "Polearm(Lance)/6",
            "Sword(Broadsword)/5",
            "Axe(Handaxe)/5",
            "Dagger/5",
            "Shield(Knight)/6",
            "Dancing/3"
        ],
        "Beggar": [
            "RHETORIC/5",
            "INTRIGUE/4",
            "Dagger/4"
        ],
        "Cartographer/Artist": [
            "Drawing/4",
            "Mathematics/2",
            "Script/5"
        ],
        "Chandler": [
            "Brewing/3",
            "Woodcraft/3",
            "Hidework/3",
            "Alchemy/2",
            "Metalcraft/2",
            "Script/5"
        ],
        "Charcoaler": [
            "Timbercraft/3",
            "Survival/3",
            "Woodcraft/2",
            "Metalcraft/2"
        ],
        "Chieftan": [
            "Tracking/4",
            "Bow/3",
            "Spear/4",
            "Dagger/4",
            "STEALTH/4",
            "Foraging/3",
            "Survival/3",
            "Hidework/2",
            "Fletching/2",
            "RHETORIC/4",
            "INTRIGUE/4"
        ],
        "Clothier": [
            "Textilecraft/4",
            "Hidework/3",
            "Jewelcraft/3",
            "Script/5"
        ],
        "Cook/Servant": [
            "INTRIGUE/4",
            "RHETORIC/4",
            "Cookery/4",
            "Textilecraft/3",
            "Herblore/2"
        ],
        "Courtesan": [
            "Lovecraft/5",
            "INTRIGUE/5",
            "SINGING/5",
            "Musician/3",
            "Dancing/3",
            "Script/5"
        ],
        "Embalmer": [
            "Embalming/4",
            "Woodcraft/2",
            "Alchemy/2",
            "Perfumery/2",
            "Script/5"
        ],
        "Farmer": [
            "Agriculture/4",
            "Weatherlore/4",
            "Animalcraft/3"
        ],
        "Fisherman": [
            "Fishing/5",
            "Seamanship/4",
            "Weatherlore/4",
            "Piloting/2",
            "Shipwright/2"
        ],
        "Gladiator": [
            "INITIATIVE/6",
            "Sword/5",
            "Shield/4",
            "Spear/5",
            "UNARMED/5",
            "Physician/2"
        ],
        "Glassworker": [
            "Glasswork/4",
            "Ceramics/2",
            "Alchemy/2",
            "Script/5"
        ],
        "Harper/Skald": [
            "SINGING/5",
            "Folklore/4",
            "ORATORY/4",
            "Lute/4",
            "Flute/3",
            "Harp/3",
            "Woodcraft/3",
            "Script/5"
        ],
        "Herald": [
            "Heraldry/4",
            "ORATORY/4",
            "RHETORIC/4",
            "INTRIGUE/5",
            "Drawing/4",
            "Language/5",
            "Script/5",
            "INITIATIVE/6",
            "Foraging/4",
            "Survival/4",
            "Physician/2",
            "Weaponcraft/2",
            "RIDING/6",
            "Polearm(Lance)/6",
            "Sword(Broadsword)/5",
            "Axe(Handaxe)/5",
            "Dagger/5",
            "Shield(Knight)/6",
            "Dancing/3"
        ],
        "Herdsman": [
            "Animalcraft/4",
            "Tracking/3",
            "Survival/3",
            "Weatherlore/4"
        ],
        "Hideworker": [
            "Hidework/4",
            "Textilecraft/2",
            "Alchemy/2"
        ],
        "Hunter/Trapper": [
            "Tracking/4",
            "Bow/3",
            "Dagger/4",
            "Bow/4",
            "STEALTH/4",
            "Foraging/3",
            "Survival/3",
            "Hidework/2",
            "Fletching/2"
        ],
        "Innkeeper": [
            "Brewing/4",
            "Cookery/4",
            "RHETORIC/4",
            "INTRIGUE/4",
            "Language/3",
            "Script/5"
        ],
        "Jeweler": [
            "Jewelcraft/4",
            "Metalcraft/3",
            "Mining/2",
            "Script/5"
        ],
        "Laborer/Longshoreman": [
            "INTRIGUE/4",
            "Seamanship/2"
        ],
        "Lady": [
            "INTRIGUE/5",
            "Folklore/4",
            "Textilecraft(Needlework)/3",
            "Dancing/3",
            "Heraldry/3",
            "Astrology/2",
            "Drawing/2"
        ],
        "Lexigrapher": [
            "Hidework(parchment&vellum)/4",
            "Alchemy(Inkcraft)/4",
            "Drawing/3",
            "Script/5",
            "Script/5"
        ],
        "Litigant": [
            "Law/4",
            "ORATORY/5",
            "RHETORIC/5",
            "INTRIGUE/5",
            "Language/3",
            "Script/5"
        ],
        "Locksmith": [
            "Lockcraft/4",
            "Metalcraft/3",
            "Woodcraft/2",
            "Script/5"
        ],
        "Mason": [
            "Masonry/4",
            "Woodcraft/3",
            "Engineering/3",
            "Mathematics/2",
            "Script/5"
        ],
        "Mercantyler": [
            "RHETORIC/5",
            "INTRIGUE/5",
            "Mathematics/3",
            "Law/2",
            "Dagger/2",
            "Language/3",
            "Script/5"
        ],
        "Metalsmith": [
            "Metalcraft/4",
            "Mining/2",
            "Weaponcraft/2"
        ],
        "Miller/Millwright": [
            "Milling/4",
            "Engineering/3",
            "Agriculture/3",
            "Script/5"
        ],
        "Miner": [
            "Mining/4",
            "Engineering/3",
            "Woodcraft/2",
            "Metalcraft/2",
            "Jewelcraft/1"
        ],
        "Ostler": [
            "Animalcraft(Horsecraft)/4",
            "RIDING/4",
            "Hidework/3"
        ],
        "Perfumer": [
            "Perfumery/4",
            "Alchemy/3",
            "Herblore/3",
            "Embalming/2",
            "Script/5"
        ],
        "Physician": [
            "Physician/4",
            "Herblore/3",
            "Alchemy/3",
            "Script/5"
        ],
        "Pilot": [
            "Piloting/4",
            "Weatherlore/4",
            "Seamanship/3",
            "Drawing/3",
            "Bow/3",
            "Shipwright/2",
            "Mathematics/2",
            "Script/5"
        ],
        "Potter": [
            "Ceramics/4",
            "Glasswork/2"
        ],
        "Prostitute/Pimp": [
            "Lovecraft/4",
            "INTRIGUE/4",
            "Dagger/4"
        ],
        "Ratter": [
            "Animalcraft(Rat)/5",
            "Animalcraft(Dog)/4",
            "Net/3",
            "Club/5",
            "Herblore/2"
        ],
        "Sage/Tutor": [
            "Folklore/4",
            "Mathematics/2",
            "Language/3",
            "Script/5",
            "Script/5"
        ],
        "Salter": [
            "Mining/3",
            "Cookery/4",
            "Survival/3",
            "Fishing/3",
            "Herblore/1"
        ],
        "Servant": [
            "INTRIGUE/4",
            "RHETORIC/4",
            "Textilecraft/3"
        ],
        "Scribe": [
            "Drawing/3",
            "Mathematics/2",
            "Language/3",
            "Script/5",
            "Script/5",
            "Script/5"
        ],
        "Seaman": [
            "Seamanship/4",
            "CLIMBING/5",
            "Club/5",
            "Dagger/4",
            "Fishing/3",
            "Weatherlore/3",
            "Piloting/2",
            "Shipwright/2",
            "Packing/3"
        ],
        "Shaman": [
            "Ritual-Tribal/4",
            "Folklore/4",
            "INTRIGUE/4",
            "MentalConflict/4",
            "RHETORIC/4",
            "Weatherlore/4",
            "Dancing/3",
            "Foraging/3",
            "ORATORY/3",
            "Embalming/2",
            "Herblore/4",
            "Physician/3",
            "Survival/3",
            "Tracking/2",
            "Spear(Spear)/2"
        ],
        "Shipwright": [
            "Shipwright/4",
            "Woodcraft/3",
            "Timbercraft/3",
            "Metalcraft/2",
            "Mathematics/2",
            "Seamanship/2",
            "Script/5"
        ],
        "Teamster": [
            "RIDING/4",
            "Animalcraft/3",
            "Whip/3",
            "Woodcraft/2",
            "Driving/4",
            "Packing/3"
        ],
        "Tentmaker": [
            "Textilecraft/3",
            "Hidework/3",
            "Woodcraft/2"
        ],
        "Thatcher": [
            "CLIMBING/5",
            "Woodcraft/3",
            "Engineering/2"
        ],
        "Thespian": [
            "Acting/4",
            "ORATORY/4",
            "SINGING/4",
            "Musician/3",
            "Drawing/3"
        ],
        "Thief": [
            "Legerdemain/4",
            "AWARENESS/5",
            "STEALTH/4",
            "INTRIGUE/4",
            "Lockcraft/3",
            "Club/5",
            "Dagger/4",
            "Acrobatics/2",
            "Searching/3"
        ],
        "Timberwright": [
            "Timbercraft/4",
            "Survival/3",
            "Weatherlore/4",
            "Woodcraft/3"
        ],
        "Toymaker": [
            "Woodcraft/4",
            "Lockcraft/3",
            "Drawing/3",
            "Hidework/2"
        ],
        "Weaponcrafter": [
            "Weaponcraft/4",
            "Sword/3",
            "Bow/3",
            "Metalcraft/3",
            "Fletching/3",
            "Mining/2"
        ],
        "Woodcrafter": [
            "Woodcraft/5",
            "Metalcraft/2",
            "Hidework/2"
        ],
        "Cleric/Agrik": [
            "Language(Azeryani)/3",
            "Script(Zerin)",
            "Ritual-Agrik/4",
            "RHETORIC/4",
            "INTRIGUE/4",
            "MentalConflict/4",
            "ORATORY/3",
            "Folklore/3",
            "Embalming/2",
            "Physician/2",
            "Law/2",
            "Drawing/2",
            "Script/5",
            "INITIATIVE/6",
            "UNARMED/4",
            "Axe(Sickle)/4",
            "Club(Mace)/4",
            "Shield/4",
            "Heraldry/3",
            "Language(Surikal)/3"
        ],
        "Cleric/Halea": [
            "Language(Karuia)/3",
            "Script(Zerin)",
            "Ritual-Halea/4",
            "RHETORIC/4",
            "INTRIGUE/4",
            "MentalConflict/4",
            "ORATORY/3",
            "Folklore/3",
            "Embalming/2",
            "Physician/2",
            "Law/2",
            "Drawing/2",
            "Heraldry/2",
            "Script/5",
            "Lovecraft/4",
            "Dancing/3",
            "Mathematics/2",
            "Musician/2",
            "Perfumery/2",
            "Language/4",
            "Script/5"
        ],
        "Cleric/Ilvir": [
            "Language(Old Jarinese)/3",
            "Script(Khruni)",
            "Ritual-Ilvir/4",
            "RHETORIC/4",
            "INTRIGUE/4",
            "MentalConflict/4",
            "ORATORY/3",
            "Folklore/3",
            "Embalming/2",
            "Law/2",
            "Drawing/2",
            "Heraldry/2",
            "Script/5",
            "Animalcraft(Ivashu)/4",
            "Drawing/3",
            "Physician/3",
            "Tarotry/2",
            "Herblore/2",
            "Language(Ivashi)/3"
        ],
        "Cleric/Larani": [
            "Language(Emela)/3",
            "Script(Khruni)",
            "Ritual-Larani/4",
            "RHETORIC/4",
            "INTRIGUE/4",
            "MentalConflict/4",
            "ORATORY/3",
            "Folklore/3",
            "Embalming/2",
            "Physician/2",
            "Law/2",
            "Drawing/2",
            "Script/5",
            "INITIATIVE/6",
            "UNARMED/4",
            "Dagger/4",
            "Sword/4",
            "Shield/4",
            "Heraldry/3"
        ],
        "Cleric/Morgath": [
            "Language(Azeri)/3",
            "Script(Nuvesarl)",
            "Ritual-Morgath/4",
            "RHETORIC/4",
            "INTRIGUE/4",
            "MentalConflict/4",
            "ORATORY/3",
            "Folklore/3",
            "Physician/2",
            "Law/2",
            "Drawing/2",
            "Heraldry/2",
            "Script/5",
            "Dagger/4",
            "Embalming/3",
            "Hidework(Human Skin)/2",
            "Woodcraft(Masks)/2",
            "Tarotry/2",
            "Language(Ormauk)/3"
        ],
        "Cleric/Naveh": [
            "Language(Besha)/3",
            "Script(Neramic)",
            "Ritual-Naveh/4",
            "RHETORIC/4",
            "INTRIGUE/4",
            "MentalConflict/4",
            "ORATORY/3",
            "Folklore/3",
            "Embalming/2",
            "Physician/2",
            "Law/2",
            "Drawing/2",
            "Heraldry/2",
            "Script/5",
            "INITIATIVE/6",
            "UNARMED/5",
            "STEALTH/5",
            "Dagger/4",
            "Acrobatics/3",
            "Legerdemain/2",
            "Lockcraft/2"
        ],
        "Cleric/Peoni": [
            "Language(Emela)/3",
            "Script(Khruni)",
            "Ritual-Peoni/4",
            "RHETORIC/4",
            "INTRIGUE/4",
            "MentalConflict/4",
            "ORATORY/3",
            "Folklore/3",
            "Embalming/2",
            "Law/2",
            "Drawing/2",
            "Heraldry/2",
            "Script/5",
            "Agriculture/4",
            "Animalcraft/3",
            "Herblore/3",
            "Physician/3",
            "Weatherlore/3",
            "Textilecraft/2"
        ],
        "Cleric/Sarajin": [
            "Language(Ivinian)/3",
            "Script(Runic)",
            "Ritual-Sarajin/4",
            "RHETORIC/4",
            "INTRIGUE/4",
            "MentalConflict/4",
            "ORATORY/3",
            "Folklore/3",
            "Embalming/2",
            "Physician/2",
            "Law/2",
            "Drawing/2",
            "Heraldry/2",
            "Script/5",
            "INITIATIVE/6",
            "UNARMED/4",
            "Axe/4",
            "Dagger/4",
            "Shield/4",
            "Runecraft/3",
            "Seamanship/2"
        ],
        "Cleric/Save-K'nor": [
            "Language(Azeri)/3",
            "Script(Tianta)",
            "Ritual-Save-K'nor/4",
            "RHETORIC/4",
            "INTRIGUE/4",
            "MentalConflict/4",
            "ORATORY/3",
            "Folklore/3",
            "Embalming/2",
            "Physician/2",
            "Law/2",
            "Drawing/2",
            "Heraldry/2",
            "Script/5",
            "Drawing/3",
            "Mathematics/3",
            "Law/3",
            "Heraldry/2",
            "Language/4",
            "Language/3",
            "Script/5"
        ],
        "Cleric/Siem": [
            "Language(Sindarin)/3",
            "Script(Selenian)",
            "Ritual-Siem/4",
            "RHETORIC/4",
            "INTRIGUE/4",
            "MentalConflict/4",
            "ORATORY/3",
            "Folklore/3",
            "Embalming/2",
            "Physician/2",
            "Law/2",
            "Drawing/2",
            "Heraldry/2",
            "Script/5",
            "Astrology/4",
            "Runecraft/3",
            "Foraging/3",
            "Survival/3",
            "Weatherlore/3",
            "Tarotry/2",
            "Musician/2",
            "Herblore/2"
        ],
        "Feudal Militia": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/4",
            "Shield(Round)/4"
        ],
        "Feudal Yeoman, Foot": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/5",
            "Sword(Shortsword)/4",
            "Dagger/4",
            "Shield(Round)/4",
            "Tactics/1"
        ],
        "Feudal Guardsman, Light": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/6",
            "Sword(Shortsword)/5",
            "Dagger/5",
            "Shield(Round)/5",
            "Tactics/2"
        ],
        "Feudal Guardsman, Heavy": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/6",
            "Sword(Falchion)/5",
            "Dagger/5",
            "Shield(Round)/5",
            "Tactics/2"
        ],
        "Feudal Yeoman, Shortbow": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Bow(Shortbow)/5",
            "Sword(Falchion)/5",
            "Dagger/5",
            "Shield(Buckler)/5",
            "Tactics/1"
        ],
        "Feudal Yeoman, Longbow": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Bow(Longbow)/5",
            "Sword(Falchion)/5",
            "Dagger/5",
            "Shield(Buckler)/5",
            "Tactics/1"
        ],
        "Feudal Knight, Medium": [
            "INITIATIVE/6",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "RIDING/6",
            "Polearm(Lance)/6",
            "Sword(Broadsword)/5",
            "Axe(Handaxe)/5",
            "Dagger/5",
            "Shield(Knight)/6",
            "Dancing/3",
            "Tactics/3"
        ],
        "Feudal Knight, Heavy": [
            "INITIATIVE/6",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "RIDING/6",
            "Polearm(Lance)/6",
            "Sword(Bastard Sword)/5",
            "Axe(Handaxe)/5",
            "Dagger/5",
            "Shield(Kite)/6",
            "Dancing/3",
            "Tactics/3"
        ],
        "Order Infantry, Light": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/6",
            "Sword(Shortsword)/5",
            "Dagger/5",
            "Shield(Round)/5",
            "Tactics/2"
        ],
        "Order Infantry, Heavy": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/6",
            "Sword(Falchion)/5",
            "Dagger/5",
            "Shield(Round)/5",
            "Tactics/2"
        ],
        "Order Archer": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Bow(Shortbow)/5",
            "Sword(Shortsword)/5",
            "Dagger/5",
            "Shield(Buckler)/5",
            "Tactics/2"
        ],
        "Order Knight, Medium": [
            "INITIATIVE/6",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "RIDING/6",
            "Polearm(Lance)/6",
            "Sword(Broadsword)/5",
            "Club(Mace)/5",
            "Dagger/5",
            "Shield(Knight)/6",
            "Dancing/3",
            "Tactics/3"
        ],
        "Order Knight, Heavy": [
            "INITIATIVE/6",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "RIDING/6",
            "Polearm(Lance)/6",
            "Sword(Bastard Sword)/5",
            "Club(Mace)/5",
            "Dagger/5",
            "Shield(Kite)/6",
            "Dancing/3",
            "Tactics/3"
        ],
        "Imperial Militia": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/4",
            "Shield(Round)/4"        
        ],
        "Imperial Legionnaire, Light": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/5",
            "Sword(Shortsword)/4",
            "Dagger/4",
            "Shield(Tower)/5",
            "Tactics/1"
        ],
        "Imperial Legionnaire, Medium": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/6",
            "Sword(Shortsword)/5",
            "Dagger/4",
            "Shield(Tower)/5",
            "Tactics/2"
        ],
        "Imperial Legionnaire, Shortbow": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Bow(Shortbow)/6",
            "Sword(Shortsword)/5",
            "Dagger/5",
            "Shield(Buckler)/5",
            "Tactics/2"
        ],
        "Patrician": [
            "INITIATIVE/6",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "RIDING/6",
            "Polearm(Lance)/6",
            "Sword(Broadsword)/5",
            "Axe(Handaxe)/5",
            "Dagger/5",
            "Shield(Kite)/6",
            "Dancing/3",
            "Tactics/3"
        ],
        "Viking Clansman, Unarmored": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/5",
            "Shield(Round)/5",
            "Dagger(Keltan)/4",
            "Seamanship/3"
        ],
        "Viking Clansman, Light": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/6",
            "Shield(Round)/6",
            "Bow((Shortbow))/5",
            "Dagger(Keltan)/5",
            "Seamanship/3",
            "Tactics/1"
        ],
        "Viking Huscarl, Medium Foot": [
            "INITIATIVE/6",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Axe(Battleaxe)/6",
            "Sword(Broadsword)/5",
            "Dagger(Keltan)/5",
            "Shield(Round)/5",
            "Seamanship/3",
            "Piloting/2",
            "Tactics/2"
        ],
        "Viking Huscarl, Light Horse": [
            "INITIATIVE/6",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "RIDING/6",
            "Polearm(Lance)/6",
            "Sword(Broadsword)/5",
            "Shield(Round)/5",
            "Seamanship/3",
            "Piloting/2",
            "Tactics/2"
        ],
        "Khuzdul Clansman": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/6",
            "Axe(Handaxe)/5",
            "Shield(Round)/5",
            "Tactics/1"
        ],
        "Khuzdul Low Guard": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/6",
            "Axe(Battleaxe)/5",
            "Dagger/5",
            "Shield(Round)/5",
            "Tactics/2"
        ],
        "Khuzdul High Guard": [
            "INITIATIVE/6",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Polearm(Poleaxe)/6",
            "Club(Mace)/5",
            "Dagger/5",
            "Shield(Round)/5",
            "Tactics/3"
        ],
        "Sindarin Ranger, Unarmored": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Bow(Hartbow)/6",
            "Sword(Longknife)/5",
            "Dagger/5",
            "Shield(Buckler)/5",
            "Tactics/2"
        ],
        "Sindarin Ranger, Light": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Bow(Hartbow)/6",
            "Sword(Longknife)/5",
            "Dagger/5",
            "Shield(Buckler)/5",
            "Tactics/2"
        ],
        "Sindarin Guardian": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "Spear/7",
            "Sword(Longknife)/6",
            "Dagger/5",
            "Shield(Round)/6",
            "Tactics/3"
        ],
        "Sindarin Horsebow": [
            "INITIATIVE/5",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "RIDING/6",
            "Bow(Hartbow)/6",
            "Polearm(Lance)/5",
            "Sword(Longknife)/5",
            "Shield(Knight)/6",
            "Dancing/3",
            "Musician/2",
            "Tactics/2"
        ],
        "Sindarin Knight": [
            "INITIATIVE/6",
            "Foraging/4",
            "Survival/4",
            "Heraldry/2",
            "Physician/2",
            "Weaponcraft/2",
            "RIDING/7",
            "Polearm(Lance)/7",
            "Sword(Longknife)/6",
            "Shield(Knight)/6",
            "Dancing/3",
            "Musician/2",
            "Tactics/3"
        ],
        "Shek-Pvar/Lyahvi*": [
            "Lyahvi/2",
            "Neutral/1",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Legerdemain/3",
            "Glasswork/3",
            "Jewelcraft/3"
        ],
        "Shek-Pvar/Lyahvi**": [
            "Lyahvi/2",
            "Neutral/2",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Legerdemain/3",
            "Glasswork/3",
            "Jewelcraft/3"
        ],
        "Shek-Pvar/Lyahvi***": [
            "Lyahvi/3",
            "Neutral/2",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Legerdemain/3",
            "Glasswork/3",
            "Jewelcraft/3"
        ],
        "Shek-Pvar/Lyahvi****": [
            "Lyahvi/3",
            "Neutral/3",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Legerdemain/3",
            "Glasswork/3",
            "Jewelcraft/3"
        ],
        "Shek-Pvar/Lyahvi*****": [
            "Lyahvi/4",
            "Neutral/3",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Legerdemain/3",
            "Glasswork/3",
            "Jewelcraft/3"
        ],
        "Shek-Pvar/Peleahn*": [
            "Peleahn/2",
            "Neutral/1",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Alchemy/3",
            "Cookery/4",
            "Metalcraft/1",
            "Weaponcraft/1"
        ],
        "Shek-Pvar/Peleahn**": [
            "Peleahn/2",
            "Neutral/2",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Alchemy/3",
            "Cookery/4",
            "Metalcraft/1",
            "Weaponcraft/1"
        ],
        "Shek-Pvar/Peleahn***": [
            "Peleahn/3",
            "Neutral/2",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Alchemy/3",
            "Cookery/4",
            "Metalcraft/1",
            "Weaponcraft/1"
        ],
        "Shek-Pvar/Peleahn****": [
            "Peleahn/3",
            "Neutral/3",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Alchemy/3",
            "Cookery/4",
            "Metalcraft/1",
            "Weaponcraft/1"
        ],
        "Shek-Pvar/Peleahn*****": [
            "Peleahn/4",
            "Neutral/3",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Alchemy/3",
            "Cookery/4",
            "Metalcraft/1",
            "Weaponcraft/1"
        ],
        "Shek-Pvar/Jmorvi*": [
            "Jmorvi/2",
            "Neutral/1",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Metalcraft/3",
            "Lockcraft/3",
            "Mining(Mineralogy)/2",
            "Weaponcraft/2"
        ],
        "Shek-Pvar/Jmorvi**": [
            "Jmorvi/2",
            "Neutral/2",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Metalcraft/3",
            "Lockcraft/3",
            "Mining(Mineralogy)/2",
            "Weaponcraft/2"
        ],
        "Shek-Pvar/Jmorvi***": [
            "Jmorvi/3",
            "Neutral/2",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Metalcraft/3",
            "Lockcraft/3",
            "Mining(Mineralogy)/2",
            "Weaponcraft/2"
        ],
        "Shek-Pvar/Jmorvi****": [
            "Jmorvi/3",
            "Neutral/3",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Metalcraft/3",
            "Lockcraft/3",
            "Mining(Mineralogy)/2",
            "Weaponcraft/2"
        ],
        "Shek-Pvar/Jmorvi*****": [
            "Jmorvi/4",
            "Neutral/3",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Metalcraft/3",
            "Lockcraft/3",
            "Mining(Mineralogy)/2",
            "Weaponcraft/2"
        ],
        "Shek-Pvar/Fyvria*": [
            "Fyvria/2",
            "Neutral/1",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Herblore/3",
            "Agriculture/3",
            "Animalcraft/3",
            "Embalming/2",
            "Foraging/3",
            "Physician/2",
            "Survival/3",
            "Tracking/2"
        ],
        "Shek-Pvar/Fyvria**": [
            "Fyvria/2",
            "Neutral/2",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Herblore/3",
            "Agriculture/3",
            "Animalcraft/3",
            "Embalming/2",
            "Foraging/3",
            "Physician/2",
            "Survival/3",
            "Tracking/2"
        ],
        "Shek-Pvar/Fyvria***": [
            "Fyvria/3",
            "Neutral/2",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Herblore/3",
            "Agriculture/3",
            "Animalcraft/3",
            "Embalming/2",
            "Foraging/3",
            "Physician/2",
            "Survival/3",
            "Tracking/2"
        ],
        "Shek-Pvar/Fyvria****": [
            "Fyvria/3",
            "Neutral/3",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Herblore/3",
            "Agriculture/3",
            "Animalcraft/3",
            "Embalming/2",
            "Foraging/3",
            "Physician/2",
            "Survival/3",
            "Tracking/2"
        ],
        "Shek-Pvar/Fyvria*****": [
            "Fyvria/4",
            "Neutral/3",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Herblore/3",
            "Agriculture/3",
            "Animalcraft/3",
            "Embalming/2",
            "Foraging/3",
            "Physician/2",
            "Survival/3",
            "Tracking/2"
        ],
        "Shek-Pvar/Odivshe*": [
            "Odivshe/2",
            "Neutral/1",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Swimming/4",
            "Fishing/3",
            "Piloting/2",
            "Seamanship/2",
            "Brewing/2"
        ],
        "Shek-Pvar/Odivshe**": [
            "Odivshe/2",
            "Neutral/2",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Swimming/4",
            "Fishing/3",
            "Piloting/2",
            "Seamanship/2",
            "Brewing/2"
        ],
        "Shek-Pvar/Odivshe***": [
            "Odivshe/3",
            "Neutral/2",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Swimming/4",
            "Fishing/3",
            "Piloting/2",
            "Seamanship/2",
            "Brewing/2"
        ],
        "Shek-Pvar/Odivshe****": [
            "Odivshe/3",
            "Neutral/3",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Swimming/4",
            "Fishing/3",
            "Piloting/2",
            "Seamanship/2",
            "Brewing/2"
        ],
        "Shek-Pvar/Odivshe*****": [
            "Odivshe/4",
            "Neutral/3",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "Swimming/4",
            "Fishing/3",
            "Piloting/2",
            "Seamanship/2",
            "Brewing/2"
        ],
        "Shek-Pvar/Savorya*": [
            "Savorya/2",
            "Neutral/1",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "MentalConflict/5",
            "Drawing/4",
            "Runecraft/3",
            "Tarotry/3"
        ],
        "Shek-Pvar/Savorya**": [
            "Savorya/2",
            "Neutral/2",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "MentalConflict/5",
            "Drawing/4",
            "Runecraft/3",
            "Tarotry/3"
        ],
        "Shek-Pvar/Savorya***": [
            "Savorya/3",
            "Neutral/2",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "MentalConflict/5",
            "Drawing/4",
            "Runecraft/3",
            "Tarotry/3"
        ],
        "Shek-Pvar/Savorya****": [
            "Savorya/3",
            "Neutral/3",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "MentalConflict/5",
            "Drawing/4",
            "Runecraft/3",
            "Tarotry/3"
        ],
        "Shek-Pvar/Savorya*****": [
            "Savorya/4",
            "Neutral/3",
            "Script/2",
            "Folklore/4",
            "Mathematics/2",
            "MentalConflict/5",
            "Drawing/4",
            "Runecraft/3",
            "Tarotry/3"
        ]
    },
    occupation_time: {
        "Alchemist": "7",
        "Animal Trainer": "3",
        "Apothecary": "6",
        "Astrologer": "4",
        "Baliff": "8",
        "Beggar": "1",
        "Cartographer/Artist": "5",
        "Chandler": "4",
        "Charcoaler": "3",
        "Chieftan": "15",
        "Clothier": "6",
        "Cook/Servant": "3",
        "Courtesan": "3",
        "Embalmer": "7",
        "Farmer": "4",
        "Fisherman": "5",
        "Gladiator": "4",
        "Glassworker": "7",
        "Harper/Skald": "7",
        "Herald": "12",
        "Herdsman": "2",
        "Hideworker": "5",
        "Hunter/Trapper": "5",
        "Innkeeper": "5",
        "Jeweler": "7",
        "Laborer/Longshoreman": "1",
        "Lady": "7",
        "Lexigrapher": "5",
        "Litigant": "7",
        "Locksmith": "6",
        "Mason": "7",
        "Mercantyler": "6",
        "Metalsmith": "6",
        "Miller/Millwright": "6",
        "Miner": "6",
        "Ostler": "5",
        "Perfumer": "6",
        "Physician": "7",
        "Pilot": "9",
        "Potter": "6",
        "Prostitute/Pimp": "1",
        "Ratter": "3",
        "Sage/Tutor": "5",
        "Salter": "4",
        "Servant": "1",
        "Scribe": "5",
        "Seaman": "5",
        "Shaman": "8",
        "Shipwright": "7",
        "Teamster": "2",
        "Tentmaker": "5",
        "Thatcher": "4",
        "Thespian": "7",
        "Thief": "3",
        "Timberwright": "6",
        "Toymaker": "5",
        "Weaponcrafter": "7",
        "Woodcrafter": "7",
        "Cleric/Agrik": "9",
        "Cleric/Halea": "9",
        "Cleric/Ilvir": "9",
        "Cleric/Larani": "9",
        "Cleric/Morgath": "9",
        "Cleric/Naveh": "9",
        "Cleric/Peoni": "9",
        "Cleric/Sarajin": "9",
        "Cleric/Save-K'nor": "9",
        "Cleric/Siem": "9",
        "Feudal Militia": "4",
        "Feudal Yeoman, Foot": "5",
        "Feudal Guardsman, Light": "5",
        "Feudal Guardsman, Heavy": "5",
        "Feudal Yeoman, Shortbow": "6",
        "Feudal Yeoman, Longbow": "6",
        "Feudal Knight, Medium": "7",
        "Feudal Knight, Heavy": "7",
        "Order Infantry, Light": "5",
        "Order Infantry, Heavy": "5",
        "Order Archer": "6",
        "Order Knight, Medium": "7",
        "Order Knight, Heavy": "7",
        "Imperial Militia": "5",
        "Imperial Legionnaire, Light": "5",
        "Imperial Legionnaire, Medium": "5",
        "Imperial Legionnaire, Shortbow": "6",
        "Patrician": "7",
        "Viking Clansman, Unarmored": "4",
        "Viking Clansman, Light": "5",
        "Viking Huscarl, Medium Foot": "6",
        "Viking Huscarl, Light Horse": "6",
        "Khuzdul Clansman": "15",
        "Khuzdul Low Guard": "20",
        "Khuzdul High Guard": "30",
        "Sindarin Ranger, Unarmored": "10",
        "Sindarin Ranger, Light": "11",
        "Sindarin Guardian": "12",
        "Sindarin Horsebow": "15",
        "Sindarin Knight": "20",
        "Shek-Pvar/Lyahvi*": "7",
        "Shek-Pvar/Lyahvi**": "7",
        "Shek-Pvar/Lyahvi***": "7",
        "Shek-Pvar/Lyahvi****": "7",
        "Shek-Pvar/Lyahvi*****": "7",
        "Shek-Pvar/Peleahn*": "7",
        "Shek-Pvar/Peleahn**": "7",
        "Shek-Pvar/Peleahn***": "7",
        "Shek-Pvar/Peleahn****": "7",
        "Shek-Pvar/Peleahn*****": "7",
        "Shek-Pvar/Jmorvi*": "7",
        "Shek-Pvar/Jmorvi**": "7",
        "Shek-Pvar/Jmorvi***": "7",
        "Shek-Pvar/Jmorvi****": "7",
        "Shek-Pvar/Jmorvi*****": "7",
        "Shek-Pvar/Fyvria*": "7",
        "Shek-Pvar/Fyvria**": "7",
        "Shek-Pvar/Fyvria***": "7",
        "Shek-Pvar/Fyvria****": "7",
        "Shek-Pvar/Fyvria*****": "7",
        "Shek-Pvar/Odivshe*": "7",
        "Shek-Pvar/Odivshe**": "7",
        "Shek-Pvar/Odivshe***": "7",
        "Shek-Pvar/Odivshe****": "7",
        "Shek-Pvar/Odivshe*****": "7",
        "Shek-Pvar/Savorya*": "7",
        "Shek-Pvar/Savorya**": "7",
        "Shek-Pvar/Savorya***": "7",
        "Shek-Pvar/Savorya****": "7",
        "Shek-Pvar/Savorya*****": "7"
    }    
}

